webappbloom/Models/Competencia.cs
namespace WebAppBloom.models;

public class Competencia{

    public int Id { get; set; }
    public string? ColunaBloom { get; set; }
    public string? LinhaBloom { get; set; }
}

webappbloom/Controllers/CompetenciaController.cs
using Microsoft.AspNetCore.Mvc;
using WebAppBloom.models;
namespace WebAppBloom.Controllers;
public class CompetenciaController : Controller{
    public IActionResult Index(){

        Competencia competencia = new Competencia();
        competencia.ColunaBloom = "Memorizar";
        competencia.LinhaBloom = "Listar";
       /* competencia.ColunaBloom = "Aplicar";
        competencia.ColunaBloom = "Avaliar";
        competencia.ColunaBloom = "Criar";*/
        ViewData["titulo"] = "Compreemder o funcionamento do Razor";
        ViewData["tablebloom"] = competencia;
        return View(); 
    }

}

webappbloom/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace WebAppBloom.Controllers;
public class HomeController : Controller{

    public IActionResult Index(){
        return View();
    }
}

webappbloom/Views/Competencia/Index.cshtml
<p>Competência:</p> @ViewData["titulo"]

@{
  var competencia = ViewData["tablebloom"] as Competencia;
}

<div class="container">
  <div class="row">
    <div class="col">
      Memorizar
    </div>
    <div class="col">
    Compreender
    </div>
    <div class="col">
    Aplicar
    </div>
    <div class="col">
    Analisar
    </div>
    <div class="col"> 
    Avaliar
    </div>
    <div class="col">
    Criar
</div>
  <!-- LINHA 2 -->
  <div class="container">
  <div class="row">
    <div class="col">
    @competencia?.LinhaBloom
    </div>
    <div class="col">
    Linha 2 - Coluna 2
    </div>
    <div class="col">
    Linha 2 - Coluna 3
    </div>
    <div class="col">
    Linha 2 - Coluna 4
    </div>
    <div class="col">
    Linha 2 - Coluna 5
    </div>
    <div class="col">
    Linha 2 - Coluna 6
</div>

 <!-- LINHA 3 -->
  <div class="container">
  <div class="row">
    <div class="col">
    Linha 3- Coluna 1
    </div>
    <div class="col">
    Linha 3 - Coluna 2
    </div>
    <div class="col">
    Linha 3 - Coluna 3
    </div>
    <div class="col">
    Linha 3 - Coluna 4
    </div>
    <div class="col">
    Linha 3 - Coluna 5
    </div>
    <div class="col">
    Linha 3 - Coluna 6
</div>

<!-- LINHA 4 -->
  <div class="container">
  <div class="row">
    <div class="col">
    Linha 4- Coluna 1
    </div>
    <div class="col">
    Linha 4 - Coluna 2
    </div>
    <div class="col">
    Linha 4 - Coluna 3
    </div>
    <div class="col">
    Linha 4 - Coluna 4
    </div>
    <div class="col">
    Linha 4 - Coluna 5
    </div>
    <div class="col">
    Linha 4 - Coluna 6
</div>
<!-- LINHA 5 -->
  <div class="container">
  <div class="row">
    <div class="col">
    Linha 5- Coluna 1
    </div>
    <div class="col">
    Linha 5 - Coluna 2
    </div>
    <div class="col">
    Linha 5 - Coluna 3
    </div>
    <div class="col">
    Linha 5 - Coluna 4
    </div>
    <div class="col">
    Linha 5 - Coluna 5
    </div>
    <div class="col">
    Linha 5 - Coluna 6
</div>
<!-- LINHA 6 -->
  <div class="container">
    
  <div class="row">
    <div class="col">
    Linha 6- Coluna 1
    </div>
    <div class="col">
    Linha 6 - Coluna 2
    </div>
    <div class="col">
    Linha 6 - Coluna 3
    </div>
    <div class="col">
    Linha 6 - Coluna 4
    </div>
    <div class="col">
    Linha 6 - Coluna 5
    </div>
    <div class="col">
    Linha 6 - Coluna 6
</div>
<!-- LINHA 7-->
  <div class="container">

  <div class="row">
    <div class="col">
    Linha 7- Coluna 1
    </div>
    <div class="col">
    Linha 7 - Coluna 2
    </div>
    <div class="col">
    Linha 7 - Coluna 3
    </div>
    <div class="col">
    Linha 7 - Coluna 4
    </div>
    <div class="col">
    Linha 7 - Coluna 5
    </div>
    <div class="col">
    Linha 7 - Coluna 6
</div>
</div>
<div class="text-center"> 

    <h1 class="display-4">Taxonomia de Bloom</h1>
    <form>
        Digite o verbo <input type="text">
        <button>Cadastrar</button>
        <div class="dropdown">
            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1"
                data-bs-toggle="dropdown" aria-expanded="false">               
                Selecione o verbo
            </button>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                <li><a class="dropdown-item" href="#">Memorizar</a></li>
                <li><a class="dropdown-item" href="#">Compreender</a></li>
                <li><a class="dropdown-item" href="#">Aplicar</a></li>
                <li><a class="dropdown-item" href="#">Avaliar</a></li>
                <li><a class="dropdown-item" href="#">Criar</a></li>
            </ul>
            
        </div>
    </form>
</div>

webappbloom/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Taxonomia de Bloom";
}

<h1>Bem-Vindo(a) ao Taxonomia de Bloom</h1>

webappbloom/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TaxoBloom</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/webappbloom.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/wwwroot">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">webappbloom</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Competencia" asp-action="Index">Competência</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>                     
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - webappbloom - <a asp-area="" asp-controller="Home" asp-action="Privacy">Samuel</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>